/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CapturedImport } from './routes/captured'
import { Route as IndexImport } from './routes/index'
import { Route as PokemonPokemonIdImport } from './routes/pokemon.$pokemonId'

// Create/Update Routes

const CapturedRoute = CapturedImport.update({
  path: '/captured',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PokemonPokemonIdRoute = PokemonPokemonIdImport.update({
  path: '/pokemon/$pokemonId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/captured': {
      preLoaderRoute: typeof CapturedImport
      parentRoute: typeof rootRoute
    }
    '/pokemon/$pokemonId': {
      preLoaderRoute: typeof PokemonPokemonIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CapturedRoute,
  PokemonPokemonIdRoute,
])

/* prettier-ignore-end */
